version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: medusa-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: superset787898
      POSTGRES_DB: medusadb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
